remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Change Blindness
description: An experiment to demonstrate the loss of ability to detect changes to an image after a quick flickering effect
